"""
Exporter: KPI & Dashboard Exporter
Produces all dashboard-ready CSV/JSON exports and the final narrative report.
"""

import json
import pandas as pd
from pathlib import Path
from datetime import datetime

EXPORTS_DIR = Path(__file__).parent.parent.parent / "data" / "exports"
REPORTS_DIR = Path(__file__).parent.parent.parent / "reports"
EXPORTS_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def export_master_dataset(df: pd.DataFrame):
    cols = [c for c in [
        "movie", "post_id", "source", "platform", "subreddit", "date",
        "text", "sentiment_label", "vader_compound", "engagement_score",
        "likes", "comments", "shares", "archetype",
        "hype_count", "concern_count", "anticipation_count",
    ] if c in df.columns]
    df[cols].to_csv(EXPORTS_DIR / "master_dataset.csv", index=False)
    print(f"    master_dataset.csv ({len(df)} rows)")


def export_daily_volume(df: pd.DataFrame):
    df = df.copy()
    df["date"] = pd.to_datetime(df["date"])
    daily = df.groupby(["movie", "date"]).agg(
        post_count=("post_id", "count"),
        avg_sentiment=("vader_compound", "mean"),
        total_engagement=("engagement_score", "sum"),
    ).reset_index()
    daily.to_csv(EXPORTS_DIR / "daily_volume.csv", index=False)
    print(f"    daily_volume.csv ({len(daily)} rows)")


def export_platform_breakdown(df: pd.DataFrame):
    platform = df.groupby(["movie", "platform", "sentiment_label"]).agg(
        count=("post_id", "count"),
        avg_engagement=("engagement_score", "mean"),
        avg_sentiment=("vader_compound", "mean"),
    ).reset_index().round(4)
    platform.to_csv(EXPORTS_DIR / "platform_breakdown.csv", index=False)

    platform_summary = df.groupby(["movie", "platform"]).agg(
        avg_sentiment=("vader_compound", "mean"),
        post_count=("post_id", "count"),
    ).reset_index().round(4)
    platform_summary.to_csv(EXPORTS_DIR / "platform_sentiment.csv", index=False)
    print(f"    platform_breakdown.csv")


def export_archetype_summary(df: pd.DataFrame):
    arch_col = "archetype" if "archetype" in df.columns else None
    if arch_col is None:
        return
    summary = df.groupby(["movie", arch_col]).agg(
        post_count=("post_id", "count"),
        avg_sentiment=("vader_compound", "mean"),
        positive_rate=("sentiment_label", lambda x: (x == "positive").mean()),
        avg_engagement=("engagement_score", "mean"),
    ).reset_index().round(4)
    summary.to_csv(EXPORTS_DIR / "archetype_summary.csv", index=False)
    print(f"    archetype_summary.csv")


def generate_final_report(
    df: pd.DataFrame,
    kpis: pd.DataFrame,
    themes: dict,
    summaries: dict,
    monitor: dict,
) -> str:
    winner     = kpis["audience_excitement_index"].idxmax()
    runner_up  = kpis["audience_excitement_index"].idxmin()
    margin     = float(kpis["audience_excitement_index"].max() - kpis["audience_excitement_index"].min())
    now        = datetime.now().strftime("%B %d, %Y")
    total      = len(df)

    report = f"""# Cultural Sentiment Intelligence — System Report
**Analyst:** Kenza En-Nassef | **Generated:** {now} | **Pipeline version:** 2.0

---

## System Overview

This report is auto-generated by the Cultural Sentiment Intelligence monitoring pipeline.
It analyzes **{total:,} posts** across Reddit, YouTube, and Google Trends for two films:
*The Devil Wears Prada 2* and *Michael*.

---

## Signal Monitor Summary

- **Total alerts triggered:** {monitor.get('total_alerts', 0)}
- **High-severity signals:** {monitor.get('high_severity', 0)}

"""

    trend_signals = monitor.get("trend_signals", [])
    for sig in trend_signals:
        report += f"- **{sig['movie']}**: Sentiment trend `{sig['sentiment_trend']}` | Volume `{sig['volume_trend']}` | Momentum `{sig['sentiment_momentum']:+.4f}`\n"

    report += f"""
---

## KPI Summary

| Metric | The Devil Wears Prada 2 | Michael |
|--------|------------------------|---------|
"""
    for col, label in [
        ("total_posts", "Total Posts"),
        ("avg_sentiment", "Avg Sentiment"),
        ("positive_mention_pct", "Positive Mention %"),
        ("negative_mention_pct", "Negative Mention %"),
        ("avg_engagement", "Avg Engagement Score"),
        ("audience_excitement_index", "**Excitement Index**"),
    ]:
        dwp_val = kpis.loc["The Devil Wears Prada 2", col] if "The Devil Wears Prada 2" in kpis.index else "—"
        mj_val  = kpis.loc["Michael", col] if "Michael" in kpis.index else "—"
        fmt = ".1f" if "pct" in col else ".4f" if isinstance(dwp_val, float) else ""
        if isinstance(dwp_val, float):
            dwp_str = f"{dwp_val:{fmt}}"
            mj_str  = f"{mj_val:{fmt}}"
        else:
            dwp_str = str(dwp_val)
            mj_str  = str(mj_val)
        report += f"| {label} | {dwp_str} | {mj_str} |\n"

    report += f"""
> **Winner — Audience Excitement Index:** *{winner}* leads by **{margin:.3f}** points.

---

## AI-Generated Audience Intelligence

"""
    for movie, summary in summaries.items():
        report += f"### {movie}\n\n{summary}\n\n---\n\n"

    report += f"""
## Narrative Themes

"""
    for movie, data in themes.items():
        report += f"### {movie}\n\n"
        for t in data.get("themes", []):
            report += f"- **{t['label']}** — {t['share']*100:.1f}% of posts | sentiment: {t['avg_sentiment']:+.3f} | keywords: {', '.join(t['keywords'][:4])}\n"
        report += "\n"

    report += """---

## Methodology

| Layer | Technology |
|-------|-----------|
| Collection | PRAW (Reddit), youtube-comment-downloader, pytrends |
| NLP | VADER compound scoring, TextBlob subjectivity |
| Theme Detection | LDA topic modeling (5 themes, TF-IDF features) |
| Segmentation | TF-IDF → PCA → K-Means (k=4, silhouette-optimized) |
| AI Summarization | OpenAI GPT-4o-mini (extractive fallback) |
| Signal Monitoring | Statistical threshold alerts (sentiment shift, volume spike) |
| Exports | CSV, JSON, PNG, Tableau .twbx |

---

*Cultural Sentiment Intelligence Pipeline v2.0 — Portfolio Project — Kenza En-Nassef*
"""
    return report


def run(df: pd.DataFrame, kpis: pd.DataFrame, themes: dict,
        summaries: dict, monitor: dict):
    print("  KPI exporter running...")
    export_master_dataset(df)
    export_daily_volume(df)
    export_platform_breakdown(df)
    export_archetype_summary(df)

    report = generate_final_report(df, kpis, themes, summaries, monitor)
    report_path = REPORTS_DIR / "final_report.md"
    report_path.write_text(report)
    print(f"    final_report.md")

    project_summary = {
        "generated_at": datetime.now().isoformat(),
        "pipeline_version": "2.0",
        "total_posts": int(len(df)),
        "movies": list(df["movie"].unique()),
        "winner_excitement_index": kpis["audience_excitement_index"].idxmax(),
        "alerts_triggered": monitor.get("total_alerts", 0),
        "kpis": kpis[["avg_sentiment", "positive_mention_pct",
                       "audience_excitement_index"]].round(4).to_dict(),
    }
    with open(REPORTS_DIR / "project_summary.json", "w") as f:
        json.dump(project_summary, f, indent=2)
    print(f"    project_summary.json")
